---
title: "day6-wrangling-tidyverse"
output: html_document
date: "2024-08-19"
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list=ls())   # clear global environment
```

```{r}
# load packages
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# read in data
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))
wb_metadata <- read_csv(here("data", "wb_indicators_metadata.csv"))
```

```{r}
# tidy the data!!

# using pivot_longer()
wb_indicators_long <- wb_indicators |>
  pivot_longer(cols = "2001 [YR2001]":"2020 [YR2020]",
               names_to = "year",
               values_to = "indicator_values")

# we need to do something about those year names
wb_data_clean <- wb_indicators_long |>
  tidyr::separate(col = year,   # separate the col year -
                  into = c("year", "year_chr"),  # into two cols named year and year chr -
                  sep = " ") |> # split the values where there is a space
  dplyr::select(-year_chr, -"Country Code", -"Series Code")  # and then we get rid of columns that we don't need


wb_data_tidy <- wb_data_clean |>
  tidyr::drop_na("Series Name") |>   # drop any rows with an NA
  tidyr::pivot_wider(names_from = "Series Name",  # you need " " when there are spaces in the name
                     values_from = indicator_values)  # lets make multiple cols for each series name

names(wb_data_tidy) <- c("country",      # lets change our variable names to be more concise without spaces
                         "year",
                         "access_clean_fuels_pp",
                         "access_electricity_pp",
                         "co2_emissions_kt",
                         "fossil_fuel_cons_pt",
                         "water_stress")

```

```{r}
# data wrangling time

us_wb <- wb_data_tidy |>
  dplyr::filter(country == "United States")  # let's look at just the data for the US

nicaragua_co2 <- wb_data_tidy |>
  dplyr::filter(country == "Nicaragua") |>
  select(year, co2_emissions_kt) # now lets just see the year and co2 emissions for nicaragua

wb_subset <- wb_data_tidy |>
  select(-c(water_stress, access_electricity_pp)) # we can also take out columns this way

wb_newnames <- wb_data_tidy |>
  rename(elec = access_electricity_pp, co2 = co2_emissions_kt)  # we can also rename columns
  

class(wb_data_tidy$year) # right now year is stored as a character
wb_data_tidy$year <- as.numeric(wb_data_tidy$year)  # this is how you change the type using base R
# or you can keep using dplyr, which is arguably better and easier to read
wb_data_tidy <- wb_data_tidy |>
  mutate(year = as.numeric(year))


wb_co2_tons <- wb_data_tidy |>
  mutate(co2_tons = co2_emissions_kt * 1000)  # maybe we want to see co2 emissions in tons. add a column!

```


```{r}
# summarizing our data

co2_total <- wb_data_tidy |>
  group_by(country) |> # for each country
  summarize(total_co2_kt = sum(co2_emissions_kt, na.rm = TRUE)) # we want a new variable(total_co2_kt) that shows the total of all co2 emissions (from every year, all together!)

co2_annual <- wb_data_tidy |>
  group_by(year) |>   # group by year
  summarize(annual_total_co2_kt = sum(co2_emissions_kt, na.rm = TRUE))  # to show total annual co2 emissions

# plot it!
ggplot(data = co2_annual, aes(x = year, y = annual_total_co2_kt)) +
  geom_line()


```

```{r}
#filtering using %in%

us_ca_data <- wb_data_tidy |>
  filter(country %in% c("United States", "Canada"))  # %in% allows you to look for any country that is in the vector we passed into filter. if instead we did ==, it would look for country names that match the full vector

data_2020 <- wb_data_tidy |>
  filter(year == 2020)

```







